import './style.css';
import firstPotraitTall from './assets/images/firstCatTall.png';
import firstPotraitWide from './assets/images/firstCatWide.jpg';
import firstProjectImg from './assets/images/weatherApp.png';
import secondProjectImg from './assets/images/battleship.png';
import thirdProjectImg from './assets/images/ticTacToe.png';
import fourthProjectImg from './assets/images/adminDashboard.png';
import fivthProjectImg from './assets/images/library.png';
import sixthProjectImg from './assets/images/signUpForm.png';
import contactImg from './assets/images/contactImg.png';

const firstPotraitHolder = document.querySelector('.potrait-holder');
const pictureElement = document.createElement('picture');
const tallSource = document.createElement('source');
tallSource.srcset = firstPotraitTall;
tallSource.media = '(max-width: 640px)';
pictureElement.appendChild(tallSource);
const wideSource = document.createElement('source');
wideSource.srcset = firstPotraitWide;
wideSource.media = '(min-width: 641px)';
pictureElement.appendChild(wideSource);
const firstPotraitImg = new Image();
firstPotraitImg.src = firstPotraitTall;
firstPotraitImg.classList.add('first-potrait-img');
pictureElement.appendChild(firstPotraitImg);
firstPotraitHolder.appendChild(pictureElement);

const one = document.querySelector('.one');
const oneImg = new Image();
oneImg.src = firstProjectImg;
one.appendChild(oneImg);
const two = document.querySelector('.two');
const twoImg = new Image();
twoImg.src = secondProjectImg;
two.appendChild(twoImg);
const three = document.querySelector('.three');
const threeImg = new Image();
threeImg.src = thirdProjectImg;
three.appendChild(threeImg);
const four = document.querySelector('.four');
const fourImg = new Image();
fourImg.src = fourthProjectImg;
four.appendChild(fourImg);
const five = document.querySelector('.five');
const fiveImg = new Image();
fiveImg.src = fivthProjectImg;
five.appendChild(fiveImg);
const six = document.querySelector('.six');
const sixImg = new Image();
sixImg.src = sixthProjectImg;
six.appendChild(sixImg);

const contactImgHolder = document.querySelector('.contact-img-holder');
const contactImage = new Image();
contactImage.src = contactImg;
contactImgHolder.appendChild(contactImage);